UPDATE `engine4_ynprofilestyler_rules` SET `preview`=0 WHERE  `rule_id`=57 LIMIT 1;

INSERT IGNORE INTO `engine4_ynprofilestyler_rules` (`rule_id`, `rulegroup_id`, `label`, `name`, `dompath`, `rule_type`, `control_type`, `default`, `preview`) VALUES (59, 4, 'Background image', 'background', '#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents ul > li', 'text', 'hidden', 'none', 0);
INSERT IGNORE INTO `engine4_ynprofilestyler_rules` (`rule_id`, `rulegroup_id`, `label`, `name`, `dompath`, `rule_type`, `control_type`, `default`, `preview`) VALUES (60, 2, 'No background', 'background', '#global_wrapper div.layout_main > div.layout_left > div.generic_layout_container, #global_wrapper div.layout_main > div.layout_right > div.generic_layout_container', 'text', 'hidden', 'none', 0);
INSERT IGNORE INTO `engine4_ynprofilestyler_rules` (`rule_id`, `rulegroup_id`, `label`, `name`, `dompath`, `rule_type`, `control_type`, `default`, `preview`) VALUES (61, 4, 'No background', 'background', '#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents ul > li', 'image', 'image', NULL, 0);

UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents ul > li' WHERE  `rule_id`=21 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents ul > li' WHERE  `rule_id`=22 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=23 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=24 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=25 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=26 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper div.tabs_alt > ul > li > a, \r\n#global_wrapper div.tabs_alt > ul > li, \r\n#global_wrapper div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=27 LIMIT 1;
UPDATE `engine4_ynprofilestyler_rules` SET `dompath`='#global_wrapper .layout_main div.tabs_alt > ul > li > a, \r\n#global_wrapper .layout_main div.tabs_alt > ul > li, \r\n#global_wrapper .layout_main div.tabs_alt > ul > li div.tab_pulldown_contents > ul > li' WHERE  `rule_id`=28 LIMIT 1;